#hashed_passwords = stauth.Hasher(['abc', 'def']).generate()
credentials:
  usernames:
    erickm:
      email: efm.physics@gmail.com
      name: Erick Martinez
      password: $2b$12$oss4NPnmgtxBXfBHeEabTe6X6EH/WExeiwmj/59eqJHjNugnF9dui
      academy: Tiger Karate
    '':
      academy: null
cookie:
  expiry_days: 30
  key: 'tiger_cookie_key' # Must be string
  name: 'tiger_cookie'
preauthorized:
  emails:
  - efm.physics@gmail.com