#hashed_passwords = stauth.Hasher(['abc', 'def']).generate()
credentials:
  usernames:
    erickm:
      email: efm.physics@gmail.com
      name: Erick Martinez
      password: $2b$12$oss4NPnmgtxBXfBHeEabTe6X6EH/WExeiwmj/59eqJHjNugnF9dui
      organization: OjaiTKD
    dan:
      email:
      name: Dan Cerminaro
      password: $2b$12$4FI3xx/rBKDFe2p9mZkqG.Tvo9qCN75BtHgRg1OgGYrt2ZZhYE77y
      organization: OjaiTKD
    '':
      organization: null
cookie:
  expiry_days: 30
  key: 'tiger_cookie_key' # Must be string
  name: 'tiger_cookie'
preauthorized:
  emails:
  - efm.physics@gmail.com